services:
  postgres:
    image: postgres:17
    container_name: digital_links_db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: